### PR TITLE
Cleanup some obsolete defadvice

### PR DESCRIPTION
**Pull request by snogge**

### CODE REVIEW

**Comment by wasamasa** [comment]
Please correct the formatting to not use tabs. Other than that, this looks like a logical change, given the bump to Emacs 25.1.

**Comment by Thaodan** [comment]
> Please correct the formatting to not use tabs. Other than that, this looks like a logical change, given the bump to Emacs 25.1.

Does the rule to not use tabs apply to all Emacs Lisp files?

**Comment by wasamasa** [comment]
Yes. To be fair, you'll be hard pressed to find any project besides Emacs itself still using them.

**Comment by snogge** [comment]
Done.  I also added a .dir-locals.el file with this setting.

**Comment by wasamasa** [comment]
Ironically, your patch did introduce more byte-compiler warnings due to the conditional definition of advice inside another function, so I've fixed that in a follow-up commit.

**Pull request merged**
